//
//  prefectures.swift
//  RegionQuiz
//
//  Created by 山田晃路 on 2023/04/05.
//
import Foundation
let prefectures = [
    ["ja": "北海道", "romaji": "hokkaido"],
    ["ja": "青森県", "romaji": "aomori"],
    ["ja": "岩手県", "romaji": "iwate"],
    ["ja": "宮城県", "romaji": "miyagi"],
    ["ja": "秋田県", "romaji": "akita"],
    ["ja": "山形県", "romaji": "yamagata"],
    ["ja": "福島県", "romaji": "fukushima"],
    ["ja": "茨城県", "romaji": "ibaraki"],
    ["ja": "栃木県", "romaji": "tochigi"],
    ["ja": "群馬県", "romaji": "gunma"],
    ["ja": "埼玉県", "romaji": "saitama"],
    ["ja": "千葉県", "romaji": "chiba"],
    ["ja": "東京都", "romaji": "tokyo"],
    ["ja": "神奈川県", "romaji": "kanagawa"],
    ["ja": "新潟県", "romaji": "niigata"],
    ["ja": "富山県", "romaji": "toyama"],
    ["ja": "石川県", "romaji": "ishikawa"],
    ["ja": "福井県", "romaji": "fukui"],
    ["ja": "山梨県", "romaji": "yamanashi"],
    ["ja": "長野県", "romaji": "nagano"],
    ["ja": "岐阜県", "romaji": "gifu"],
    ["ja": "静岡県", "romaji": "shizuoka"],
    ["ja": "愛知県", "romaji": "aichi"],
    ["ja": "三重県", "romaji": "mie"],
    ["ja": "滋賀県", "romaji": "shiga"],
    ["ja": "京都府", "romaji": "kyoto"],
    ["ja": "大阪府", "romaji": "osaka"],
    ["ja": "兵庫県", "romaji": "hyogo"],
    ["ja": "奈良県", "romaji": "nara"],
    ["ja": "和歌山県", "romaji": "wakayama"],
    ["ja": "鳥取県", "romaji": "tottori"],
    ["ja": "島根県", "romaji": "shimane"],
    ["ja": "岡山県", "romaji": "okayama"],
    ["ja": "広島県", "romaji": "hiroshima"],
    ["ja": "山口県", "romaji": "yamaguchi"],
    ["ja": "徳島県", "romaji": "tokushima"],
    ["ja": "香川県", "romaji": "kagawa"],
    ["ja": "愛媛県", "romaji": "ehime"],
    ["ja": "高知県", "romaji": "kochi"],
    ["ja": "愛媛県", "romaji": "ehime"],
    ["ja": "高知県", "romaji": "kochi"],
    ["ja": "福岡県", "romaji": "fukuoka"],
    ["ja": "佐賀県", "romaji": "saga"],
    ["ja": "長崎県", "romaji": "nagasaki"],
    ["ja": "熊本県", "romaji": "kumamoto"],
    ["ja": "大分県", "romaji": "oita"],
    ["ja": "宮崎県", "romaji": "miyazaki"],
    ["ja": "鹿児島県", "romaji": "kagoshima"],
    ["ja": "沖縄県", "romaji": "okinawa"]
] //　都道府県
